### ISSUE TITLE
Self-assigning in Southern-islands code

### ISSUE THREAD

**Issue by sunyifan112358** [Multi2Sim/multi2sim#22]
https://github.com/Multi2Sim/multi2sim/blob/master/src/arch/southern-islands/emulator/Wavefront.h#L289

and similarly, line 302. The setter does not work, since the input argument is not used.

**Comment by amirkavyan** [comment]
@sunyifan112358, Thank you. 

I suspect neither of these two wrong self-assigners have an impact on the simulation results. For the waitcnt, we set the mem_wait of the WavefrontPool _entry_  instead of the wavefront itself. 

setVectorMemoryGlobalCoherency is mentioned in the code to be redundant for now (Since memory is not modeled for the emulator, and NMOESI is taking care of coherency in the timinig(?!)). 

Either way I changed them and will commit. We can run the tests again and see if they are running successfully

**Comment by amirkavyan** [comment]
Seems the issue is resolved.
