### ISSUE TITLE
Cache Eviction

### ISSUE THREAD

**Issue by sing0512** [Multi2Sim/multi2sim#31]
I think the current cache eviction implementation is incorrect. When a cache block is replaced, the old block is written back as long as it is dirty. In m2s, a block will be written back if its state is not invalid. It is pointless to write back the data if the state is shared or exclusive.

**Comment by amirkavyan** [comment]
It is not pointless.

We have look into this issue before. Although it can sometimes be inefficient (only in E state), it is not wrong. The main reason a message is sent back to the lower level during the eviction (in any state) is to let the lower level know that one sharer should be removed from the list of the sharers of the block. This in turn eventually reduces the messages on the network in future interactions (since sharer list is updated and the lower level knows exactly which upper level cache holds the block). 

However I we should only send a single 8B message (known as control message) to the lower level and not the entire data, if the data is not dirty (which is 8B + a cacheline -- 72B). 
You should check the message size, and if the message size is wrong reopen this issue, if required
