### ISSUE TITLE
OpenCL code deadlock when runnign multicore simulation

### ISSUE THREAD

**Issue by sing0512** [Multi2Sim/multi2sim#33]
When an OpenCL application run on a multicore platform, it will deadlock. The opencl_x86_device_create() function in /runtime/opencl/x86-device.c never returns. This problem only happens when simulating multiple cores.

**Comment by amirkavyan** [comment]
Can you provide a [MRE](https://en.wikipedia.org/wiki/Minimal_Working_Example) and the command you used to create the problem?

As you may know creating programs and context is time consuming (specially creating one to recreate an issue -- whatever that issues is). So if you provide the files and the command that creates the issue, we can recreate it faster, and consequently resolve it faster.

**Comment by amirkavyan** [comment]
That example is for fused devices. The fused devices are not yet ported from multi2sim 4.2 to multi2sim 5.0. The plan is to do the porting in the development branch, and release this feature in 5.1. That is why you need to change the device to southern-islands, manually, otherwise it will stay fused with no support in the ABI/Driver
